baseURL = 'https://workshop.relationship-geeks.de'
languageCode = 'en-us'
title = 'workshops|Relationship Geeks'
enableRobotsTXT = true

#theme = ["github.com/4s3ti/hugo-theme-hello-4s3ti"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  customCSS = ["39c3.css", "custom.css"]
  defaultTheme = "dark"
  EnableThemeToggle = false
  EnableSharingButtons = false
  EnableGlobalLanguageMenu = false
  backgroundImage = "img/rg_logo_bg_1920.webp"
  backgroundEffects = true
  showPosts = true
  tags = false
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  contentTypeName = "workshops"
  logo = { logoMark = "workshops $", logoText = "relationship_geeks", logoCursorColor = "#00ff00" }

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://events.ccc.de/congress/2025/hub/en/assembly/detail/relationship-geeks"
    weight = 2

#  [[menu.main]]
#    identifier = "workshops"
#    name = "Workshops"
#    url = "/workshops"
#    weight = 1
  [[menu.main]]
    identifier = "recommendations"
    name = "Syllabus"
    url = "recommendations"
    weight = 2

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "archive"
    weight = 3
